AWSTemplateFormatVersion: 2010-09-09
Description: Athena Frontend Template
Parameters:
  Tenant:
    Description: Tenant that we want to deploy Athena Project
    Type: String
  FEDomain:
    Description: Frontend Root Domain which hosted in Route53
    Type: String
  FEHostedZoneId:
    Description: Route53 Hosted Zone for Frontend
    Type: String
  FESSLCertificateId:
    Description: "The ARN of the SSL certificate to use for the Frontend CloudFront"
    Type: String
Resources:
  FEBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Tenant}.${FEDomain}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, POST, PUT, DELETE]
            AllowedOrigins: ["*"]
            Id: defaultCORSRuleId1
            MaxAge: 3600
  FECloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn: FEBucket
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt FEBucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: "http2"
        DefaultRootObject: index.html
        Aliases:
          - !Sub ${Tenant}.${FEDomain}
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref FESSLCertificateId
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016

  FERoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref FEHostedZoneId
      Name: !Sub ${Tenant}.${FEDomain}
      Type: A
      AliasTarget:
        # Specify Z2FDTNDATAQYW2. This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution.
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt FECloudfront.DomainName

Outputs:
  BucketName:
    Description: Name of S3 bucket to hold website content
    Value: !Ref FEBucket
  CloudfrontEndpoint:
    Description: Endpoint for Cloudfront distribution
    Value: !GetAtt FECloudfront.DomainName
  CloudFrontId:
    Description: CloudFront Distribution Id
    Value: !Ref FECloudfront
  FEURL:
    Description: Athena Website URL
    Value: !Sub https://${FERoute53Record}
