AWSTemplateFormatVersion: 2010-09-09
Description: Athena WebQuery Template
Parameters:
  Tenant:
    Description: Tenant that we want to deploy Athena Project
    Type: String
  WQDomain:
    Description: Frontend Root Domain which hosted in Route53
    Type: String
  WQHostedZoneId:
    Description: Route53 Hosted Zone for Frontend
    Type: String
  WQSSLCertificateId:
    Description: "The ARN of the SSL certificate to use for the Frontend CloudFront"
    Type: String
Resources:
  WQBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub webquery-${Tenant}.${WQDomain}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, POST, PUT, DELETE]
            AllowedOrigins: ["*"]
            Id: defaultCORSRuleId1
            MaxAge: 3600
  WQCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt WQBucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: "http2"
        DefaultRootObject: index.html
        Aliases:
          - !Sub webquery-${Tenant}.${WQDomain}
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref WQSSLCertificateId
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016

  WQRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref WQHostedZoneId
      Name: !Sub webquery-${Tenant}.${WQDomain}
      Type: A
      AliasTarget:
        # Specify Z2FDTNDATAQYW2. This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution.
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt WQCloudfront.DomainName

Outputs:
  BucketName:
    Description: Name of S3 bucket to hold website content
    Value: !Ref WQBucket
  CloudfrontEndpoint:
    Description: Endpoint for Cloudfront distribution
    Value: !GetAtt WQCloudfront.DomainName
  CloudFrontId:
    Description: CloudFront Distribution Id
    Value: !Ref WQCloudfront
  WQURL:
    Description: Athena WebQuery Website URL
    Value: !Sub https://${WQRoute53Record}
