apiVersion: v1
kind: Service
metadata:
  name: geoserverservice
  labels:
    svc: geoserverservice
spec:
  type: NodePort
  selector:
    app: geoserverservice
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8080
    name: http

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoserver-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08da9fd022e8d61bd:/demeleg

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-data-claim
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserverservice
  labels:
    name: geoserverservice
  annotations:
    prometheus.io/path: "/actuator/prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserverservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geoserverservice
    spec:
      containers:
      - name: geoserverservice
        image: 696952606624.dkr.ecr.us-east-2.amazonaws.com/athena/geoserver:2.18.3
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /geo_data
          name: geo-data
        imagePullPolicy: Always
      volumes:
        - name: geo-data
          persistentVolumeClaim:
            claimName: geoserver-data-claim

