apiVersion: v1
kind: Service
metadata:
  namespace: ktvn
  name: overlayservice
  labels:
    svc: overlayservice
spec:
  selector:
    app: overlayservice
  ports:
  - protocol: TCP
    port: 8076
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ktvn
  name: overlayservice

  labels:
    name: overlayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overlayservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: overlayservice
        app: overlayservice
    spec:
      containers:
      - image: 696952606624.dkr.ecr.us-east-2.amazonaws.com/athena/overlay:9c23ea133c82e19440b0bf5815321c8d096f56dd
        name: overlayservice
        command: ["/bin/sh", "-c"]
        args: 
          - . /home/athena/athena.env;java -Dserver.tomcat.mbeanregistry.enabled=true -Dspring.profiles.active=eks -jar -XX:+UseG1GC -Xms256m -Xmx1024m  /home/athena/app.jar --overlay.database.server=${DB_HOST} --geocode.database.server=${DB_HOST}
        ports:
        - containerPort:  8076
        volumeMounts:
        - mountPath: /home/athena/athena.env
          name: athenaenv
          subPath: athena.env
        imagePullPolicy: Always
      volumes:
        - name: athenaenv
          configMap:
            defaultMode: 420
            name: release
      restartPolicy: Always
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: overlayservice
  namespace: ktvn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: overlayservice
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: jvm_threads_live_threads
      targetAverageValue: 2500
  - type: Pods
    pods:
      metricName: tomcat_threads_current_threads
      targetAverageValue: 50
