#!/usr/bin/env python3
import boto3
import sys
from botocore.config import Config

if __name__ == "__main__":
	try:
		DEFAULT_REGION = 'us-east-2'
		# Should refactor this using argparse module
		aws_region = DEFAULT_REGION
		prefix_cfn_stack = sys.argv[1]
		if len(sys.argv) > 2:
			aws_region = sys.argv[2]
		if len(sys.argv) > 3:
			aws_profile = sys.argv[3]
			session = boto3.Session(profile_name=aws_profile)
		else:
			session = boto3.Session()

		aws_config = Config(region_name=aws_region)
		aws_cfn = session.client('cloudformation', config=aws_config)

		paginator = aws_cfn.get_paginator('list_stacks')
		cfn_resps = paginator.paginate(StackStatusFilter=['CREATE_COMPLETE', 'UPDATE_COMPLETE', 'ROLLBACK_COMPLETE'])
		for page in cfn_resps:
			stack = page['StackSummaries']
			for cfn_resp in stack:
				if prefix_cfn_stack in cfn_resp['StackName']:
					stack_name = cfn_resp['StackName']
					if stack_name:
						print(stack_name)

	except Exception as err:
		print(err)
