#!/usr/bin/env python3
import sys

if __name__ == "__main__":
  instance_id = sys.argv[1]
  service_name = sys.argv[2]
  build_version = sys.argv[3]
  service_versions = sys.argv[4]

  #print("instance_id: ", instance_id)
  #print("service_name: ", service_name)
  #print("build_version: ", build_version)
  print(f"{instance_id}.{service_name}.{build_version}|{service_versions}")
