#!/bin/bash -xe
filename=$1
fe_version=$2
be_env=$3
env=$4

# Update BE URL
if [ -n "$env" ] && [ $env = "prod" ]; then
  jq ".apiHost = \"https://ath-be-${be_env}.karrostech.net/api/webquery\"" /tmp/${filename}.${be_env}.json  | sponge /tmp/${filename}.${be_env}.json
else
  jq ".apiHost = \"https://ath-be-${be_env}.athena-nonprod.com/api/webquery\"" /tmp/${filename}.${be_env}.json  | sponge /tmp/${filename}.${be_env}.json
fi
# Update FE version
jq ".version = \"${fe_version}\"" /tmp/${filename}.${be_env}.json  | sponge /tmp/${filename}.${be_env}.json
