apiVersion: v1
kind: Service
metadata:
  namespace: uat01
  name: geocodeservice
  labels:
    svc: geocodeservice
spec:
  selector:
    app: geocodeservice
  ports:
  - protocol: TCP
    port: 8095
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat01
  name: geocodeservice

  labels:
    name: geocodeservice
  annotations:
    prometheus.io/path: "/actuator/prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geocodeservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: geocodeservice
        app: geocodeservice
    spec:
      containers:
      - image: 696952606624.dkr.ecr.us-east-2.amazonaws.com/athena/geocodeservice:138eb15d72343d1f9a91b87770bc8d6c99e9d13e
        name: geocodeservice
        command: ["/bin/sh", "-c"]
        args: 
          - . /home/athena/athena.env;java -Dserver.tomcat.mbeanregistry.enabled=true -Dcom.sun.management.jmxremote.port=6001 -Dspring.profiles.active=eks -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=6001 -jar -XX:+UseG1GC -Xms256m -Xmx1536m /home/athena/app.jar --spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/Athena
        ports:
        - containerPort:  8095
          name: geocodeservice
        volumeMounts:
        - mountPath: /home/athena/athena.env
          name: athenaenv
          subPath: athena.env
        imagePullPolicy: Always
      volumes:
        - name: athenaenv
          configMap:
            defaultMode: 420
            name: release
      restartPolicy: Always

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: geocodeservice
  namespace: uat01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geocodeservice
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: jvm_threads_live_threads
      targetAverageValue: 2500
  - type: Pods
    pods:
      metricName: tomcat_threads_current_threads
      targetAverageValue: 50
