apiVersion: v1
kind: Service
metadata:
  namespace: uat01
  name: plannedrolloverservice
  labels:
    svc: plannedrolloverservice
spec:
  selector:
    app: plannedrolloverservice
  ports:
  - protocol: TCP
    port: 8100
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat01
  name: plannedrolloverservice

  labels:
    name: plannedrolloverservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plannedrolloverservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: plannedrolloverservice
        app: plannedrolloverservice
    spec:
      containers:
      - image: 696952606624.dkr.ecr.us-east-2.amazonaws.com/athena/plannedrolloverservice:41d0bc05b8eda5174151cdb1ead8d9af2bee3fdd
        name: plannedrolloverservice
        command: ["/bin/sh", "-c"]
        args: 
          - . /home/athena/athena.env;java -Dtenantconfig.api.url=https://athenagateway-p01-demo.usw2.karrostech.net/api/ -Dspring.profiles.active=eks -Dkarros.api.key=9d6c3f85669a40cd1b1fa4635b049b92bb04c881 -Dathena.tenant.id=${TENANT_ID} -jar -XX:+UseG1GC -Xms256m -Xmx1536m /home/athena/app.jar
        ports:
        - containerPort:  8100
          name: plannedrollover
        volumeMounts:
        - mountPath: /home/athena/athena.env
          name: athenaenv
          subPath: athena.env
        imagePullPolicy: Always
      volumes:
        - name: athenaenv
          configMap:
            defaultMode: 420
            name: release
      restartPolicy: Always

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: plannedrolloverservice
  namespace: uat01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plannedrolloverservice
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: jvm_threads_live_threads
      targetAverageValue: 2500
  - type: Pods
    pods:
      metricName: tomcat_threads_current_threads
      targetAverageValue: 50
