---
# Playbook for adding new Athena Service into EC2 Instance

- hosts: type_backend
  remote_user: ubuntu
  become: yes
  gather_facts: false
  vars: 
    ansibile_ssh_private_key_file: ~/.ssh/athena-devops.pem
    tasks:
    - name: Ensures /opt/athena/run dir exists
      file: 
        path: /opt/prometheus/node_exporter
        state: directory
    - name: Add run script
      copy:
        src: start.sh
        dest: /opt/prometheus/node_exporter
        mode: 0755
    - name: Add SystemD service
    - name: Start & Enable service