apiVersion: v1
kind: Service
metadata:
  namespace: fr
  name: importingservice
  labels:
    svc: importingservice
spec:
  selector:
    app: importingservice
  ports:
  - protocol: TCP
    port: 8097
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fr
  name: importingservice

  labels:
    name: importingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: importingservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: importingservice
        app: importingservice
    spec:
      containers:
      - image: 696952606624.dkr.ecr.us-east-2.amazonaws.com/athena/importservice:dockerize-e0737a5
        name: importingservice
        command: ["/bin/sh", "-c"]
        args: 
          - . /home/athena/athena.env;java -Dspring.profiles.active=eks -jar -XX:+UseG1GC -Xms256m -Xmx1024m  /home/athena/app.jar --spring.data.mongodb.host=${CACHE_HOST}
        ports:
        - containerPort:  8097
        volumeMounts:
        - mountPath: /home/athena/athena.env
          name: athenaenv
          subPath: athena.env
        imagePullPolicy: Always
      volumes:
        - name: athenaenv
          configMap:
            defaultMode: 420
            name: release
      restartPolicy: Always