apiVersion: v1
kind: Service
metadata:
  namespace: fr
  name: overlayservice
  labels:
    svc: overlayservice
spec:
  selector:
    app: overlayservice
  ports:
  - protocol: TCP
    port: 8076
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fr
  name: overlayservice

  labels:
    name: overlayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overlayservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: overlayservice
        app: overlayservice
    spec:
      containers:
      - image: 696952606624.dkr.ecr.us-east-2.amazonaws.com/athena/overlay:dockerize-021feb8
        name: overlayservice
        command: ["/bin/sh", "-c"]
        args: 
          - . /home/athena/athena.env;java -Dspring.profiles.active=eks -jar -XX:+UseG1GC -Xms256m -Xmx1024m  /home/athena/app.jar --overlay.database.server=${DB_HOST} --geocode.database.server=${DB_HOST}
        ports:
        - containerPort:  8076
        volumeMounts:
        - mountPath: /home/athena/athena.env
          name: athenaenv
          subPath: athena.env
        imagePullPolicy: Always
      volumes:
        - name: athenaenv
          configMap:
            defaultMode: 420
            name: release
      restartPolicy: Always