#!/usr/bin/env python3
import boto3
import sys
import os
from botocore.config import Config

if __name__ == "__main__":
    try:
        project = 'athena'
        tenant = sys.argv[1]
        release_version = sys.argv[2]
        filters = [
            {'Name': 'tag:project', 'Values': [project]},
            {'Name': 'tag:image_type', 'Values': ['release']},
            {'Name': 'tag:release_version', 'Values': [release_version]}
        ]

        # Get image_id
        config = Config(region_name='eu-west-3')
        ec2 = boto3.client('ec2', config=config)
        response = ec2.describe_images(Filters=filters)
        images = response.get('Images')
        if images:
            image = images[0]
            if image:
                image_id = image.get('ImageId')
                print(
                        f'==> Update new AMI into CFN Stack for tenant: {tenant} with AMI: {image_id}')
                res = os.system(f'/usr/local/bin/update_stack_release_fr {tenant} {image_id}')
                print('deploy-nonprod.res', res)
                if res != 0:
                    exit(1)
    except Exception as e:
        print("deploy-nonprod.failed: ", e)
        exit(1)

