#!/usr/bin/python3
import boto3

def get_boto3_client():
    try:
        client = boto3.client(
            'workspaces',
            aws_access_key_id="AKIA2QFC7XYSHBXK24EU",
            aws_secret_access_key="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",
            region_name = 'ap-southeast-1'
        )
        return client
    except Exception as e:
        print("get_boto3_client.error", e)
        raise e

def restart_workspace(ws_id):
    try:
        client = get_boto3_client()
        response = client.reboot_workspaces(
            RebootWorkspaceRequests=[
                {
                    'WorkspaceId': ws_id
                },
            ]
        )
        return response
    except Exception as e:
        print("restart_workspace.error", e)
        raise e
if __name__ == "__main__":
    ws_id = "ws-5sy5kbnq0"
    restart_workspace(ws_id)

