apiVersion: v1
kind: Service
metadata:
  namespace: development-fr
  name: reportservice
  labels:
    svc: reportservice
spec:
  selector:
    app: reportservice
  ports:
  - protocol: TCP
    port: 8084
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development-fr
  name: reportservice

  labels:
    name: reportservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: reportservice
        app: reportservice
    spec:
      containers:
      - image: 696952606624.dkr.ecr.us-east-2.amazonaws.com/athena/reportservice:dockerize-0ef7b1f
        name: reportservice
        command: ["/bin/sh", "-c"]
        args: 
          - . /home/athena/athena.env;java -Dspring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/Athena -Dspring.data.mongodb.host=${CACHE_HOST} -jar -XX:+UseG1GC -Xms256m -Xmx1536m /home/athena/app.jar
        ports:
        - containerPort:  8084
          name: reportservice
        volumeMounts:
        - mountPath: /home/athena/athena.env
          name: athenaenv
          subPath: athena.env
        imagePullPolicy: Always
      volumes:
        - name: athenaenv
          configMap:
            defaultMode: 420
            name: release
      restartPolicy: Always