// Job: athena-deploy-prod-env
node {
    beReleasesList = sh (script: 'cat ${JENKINS_HOME}/athena/versions/release_backend.txt', returnStdout: true).trim()
    feReleasesList = sh (script: 'cat ${JENKINS_HOME}/athena/versions/release_frontend.txt', returnStdout: true).trim()
    timezoneList = sh (script: 'cat ${JENKINS_HOME}/athena/config/timezone-list.txt', returnStdout: true).trim()
}
pipeline {
  agent any

  parameters {
    choice(name: 'REGION', choices: ['us-east-2'])
    string(name: 'TENANT', description: 'Tenant should not be duplicated with the existing tenants!!! Tenant must contain only alphabet and hyphen!!!')
    string(name: 'TENANT_ID', defaultValue: '', description: 'Tenant ID to create environment. It is required when IS_NEW_TENANT is No!')
    choice(name: 'TIMEZONE', choices: "${timezoneList}", description: 'Choose a Timezone for new Tenant. It is only valid when IS_NEW_TENANT is Yes!')
    string(name: 'EMAIL', description: 'Admin User Email for managing Tenant.')
    string(name: 'FIRST_NAME', description: 'Admin User First Name. It is only valid when IS_NEW_TENANT is Yes!')
    string(name: 'LAST_NAME', description: 'Admin User Last Name. It is only valid when IS_NEW_TENANT is Yes!')
    choice(name: 'FE_RELEASE_VERSION', choices: "${feReleasesList}", description: 'Release Version of Backend to get AMI for Deployment Backend Servicess. Ex: BE-x.x.x')
    choice(name: 'BE_RELEASE_VERSION', choices: "${beReleasesList}", description: 'Release Version of Backend to get AMI for Deployment Backend Servicess. Ex: BE-x.x.x')
    choice(name: 'BE_INSTANCE_TYPE', choices: ['m5.large', 'm5.xlarge', 'm5.2xlarge'])
    choice(name: 'USE_DEBEZIUM_CONNECTOR', choices: ['no', 'yes'])
    choice(name: 'CQ_INSTANCE_TYPE', choices: ['t3.small', 't3.large', 't3.xlarge'])
    choice(name: 'DB_INSTANCE_TYPE', choices: ['db.t3.small', 'db.t3.medium', 'db.t3.large', 'db.m5.large', 'db.m5.xlarge'])
    choice(name: 'DB_ALLOCATE_STORAGE', choices: ['50', '100', '150', '200', '250'], description: 'DB Allocate Storage')
    choice(name: 'DB_MAXALLOCATE_STORAGE', choices: ['100', '150', '200', '250', '300'], description: 'Maximum DB Allocate Storage, this value must be greater than DB_ALLOCATE_STORAGE')
    string(name: 'DB_SNAPSHOT_ID', defaultValue: 'arn:aws:rds:us-east-2:690893158275:snapshot:athena-base-rds-2-082-1-24-0', description: 'RDS Snapshot ID to deploy base database into RDS')
    password(name: 'DB_MASTER_PASSWORD', defaultValue: '2ASU0sGt9UXz', description: 'Password for user postgres of RDS')
  }

  environment {
    PROJECT = 'athena'
    ENV = 'prod'
    AUTHOR = 'devops'
    STACK_NAME = "${PROJECT}-${params.TENANT}"
    VPC_STACK_NAME = 'edulogvn-prod-vpc'
    KEYPAIR = 'edulogvn-devops'
    DOMAIN = 'etstack.io'
    HOSTEDZONE_ID = 'Z12KP7UYAVP23S'
    SSL_CERTIFICATE_ARN = 'arn:aws:acm:us-east-1:690893158275:certificate/9dce5e22-6e5e-470f-9b42-3d7862df8690'
    BE_DOMAIN = 'karrostech.net'
    BE_HOSTEDZONE_ID = 'Z33NWCVN5UFMNZ'
    BE_SSL_CERTIFICATE_ARN = 'arn:aws:acm:us-east-2:690893158275:certificate/9978ae1d-16b0-4162-9add-3fb57083d06d'
    CQ_AMI_ID = 'ami-044ad7a1038fee433'
    KARROS_GATEWAY = 'athenagateway-p01-prod.usw1.karrostech.net'
    KEYCLOAK_DOMAIN = 'accounts.karrostech.net'
    KEYCLOAK_ID = 'athena'
    KEYCLOAK_SECRET = '2224875d-7c29-430f-8e11-471be0499782'
    // DEVOPS BUCKET 
    S3_DEVOPS = 'edulog-athena-prod-devops'
    // ARTIFACTS BUCKET
    S3_ARTIFACTS = 'edulog-athena-prod-artifacts'
    S3_ARTIFACTS_PREFIX = 'athena/frontend/release'
    FE_CONFIG_FILE = 'systemconfig'
    // TEMPLATE DIRECTORY
    MASTER_TEMPLATE = "cloudformation/athena/templates/athena.yml"
    OUTPUT_MASTER_TEMPLATE = "athena.${params.TENANT}.yaml"
    // AWS COMMANDS
    AWS_CMD = '/usr/local/bin/aws --profile prod'
  }


  stages {

    stage('Checkout') {
      steps {
        echo "=> Checkout IaC Repository"
        script {
          def scmVars = checkout([
            $class: 'GitSCM', 
            branches: [[name: '*/master']],
            userRemoteConfigs: [[
              url: 'git@github.com:eduloginc/devops-iac-athena.git', 
              credentialsId: 'eduloginc-git-tankhuu'
              ]]
          ])
        }
      }
    }

    stage('Package Templates') {
        steps {
          script {
            // Set dynamic s3 prefix
            env.S3_DEVOPS_PREFIX = "iac/cloudformation/athena/${ENV}/${TENANT}"
          }
          echo "=> Package CFN Templates"
          sh """
            #!/bin/bash -xe
            $AWS_CMD --region ${params.REGION} cloudformation package --template-file ${MASTER_TEMPLATE} \
            --s3-bucket ${S3_DEVOPS} --s3-prefix ${S3_DEVOPS_PREFIX} \
            --force-upload --output-template-file ${OUTPUT_MASTER_TEMPLATE}
          """
          echo "=> Upload master template to S3"
          sh """
            #!/bin/bash -xe
            $AWS_CMD s3 cp ${OUTPUT_MASTER_TEMPLATE} s3://${S3_DEVOPS}/${S3_DEVOPS_PREFIX}/${OUTPUT_MASTER_TEMPLATE}
          """
        }
    }

    stage('Create CFN Stacks') {
      environment {
        BE_AMI_ID = sh(script: '/usr/local/bin/get-ami-from-tag ${BE_RELEASE_VERSION} ${REGION} ${ENV}', returnStdout: true).trim()
        TEMPLATE_URL = "https://${S3_DEVOPS}.s3.us-east-2.amazonaws.com/${S3_DEVOPS_PREFIX}/${OUTPUT_MASTER_TEMPLATE}"
      }
      steps {
        // Create CFN Master Stack
        echo "=> Creating CFN Stacks with ${BE_AMI_ID}"
        sh """
          #!/bin/bash -xe
          $AWS_CMD --region ${REGION} cloudformation create-stack \
          --stack-name ${STACK_NAME} \
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
          --template-url ${TEMPLATE_URL} \
          --tags \
            Key=environment,Value=${ENV} \
            Key=project,Value=${PROJECT} \
            Key=author,Value=${AUTHOR} \
            Key=tenant,Value=${params.TENANT} \
          --parameters \
            ParameterKey=KeyPairName,ParameterValue=${KEYPAIR} \
            ParameterKey=Tenant,ParameterValue=${params.TENANT} \
            ParameterKey=TenantId,ParameterValue=${TENANT_ID} \
            ParameterKey=Env,ParameterValue=${ENV} \
            ParameterKey=VPCStackName,ParameterValue=${VPC_STACK_NAME} \
            ParameterKey=BackendAMIId,ParameterValue=${BE_AMI_ID}  \
            ParameterKey=FEDomain,ParameterValue=${DOMAIN}  \
            ParameterKey=FEHostedZoneId,ParameterValue=${HOSTEDZONE_ID} \
            ParameterKey=FESSLCertificateId,ParameterValue=${SSL_CERTIFICATE_ARN} \
            ParameterKey=BEDomain,ParameterValue=${BE_DOMAIN}  \
            ParameterKey=BEHostedZoneId,ParameterValue=${BE_HOSTEDZONE_ID} \
            ParameterKey=BESSLCertificateId,ParameterValue=${BE_SSL_CERTIFICATE_ARN} \
            ParameterKey=BackendInstanceType,ParameterValue=${BE_INSTANCE_TYPE}  \
            ParameterKey=CQAMIID,ParameterValue=${CQ_AMI_ID}  \
            ParameterKey=CQInstanceType,ParameterValue=${CQ_INSTANCE_TYPE}  \
            ParameterKey=DBInstanceClass,ParameterValue=${DB_INSTANCE_TYPE}  \
            ParameterKey=DBAllocatedStorage,ParameterValue=${DB_ALLOCATE_STORAGE}  \
            ParameterKey=DBMaxAllocatedStorage,ParameterValue=${DB_MAXALLOCATE_STORAGE}  \
            ParameterKey=DBMasterUserPassword,ParameterValue=${params.DB_MASTER_PASSWORD} \
            ParameterKey=DBSnapshotIdentifier,ParameterValue=${params.DB_SNAPSHOT_ID} \
            ParameterKey=KarrosGateway,ParameterValue=${KARROS_GATEWAY} \
            ParameterKey=KeycloakDomain,ParameterValue=${KEYCLOAK_DOMAIN} \
            ParameterKey=KeycloakId,ParameterValue=${KEYCLOAK_ID} \
            ParameterKey=KeycloakSecret,ParameterValue=${KEYCLOAK_SECRET} \
            ParameterKey=UseConnector,ParameterValue=${USE_DEBEZIUM_CONNECTOR}
        """
      }
    }

    stage('Wait for CFN Stacks Creation COMPLETE') {
      steps {
        echo "=> Wait for Master Stack Name: ${STACK_NAME} COMPLETE"
        script {
          try {
            sh """
              #!/bin/bash -xe
              $AWS_CMD --region ${REGION} cloudformation wait stack-create-complete --stack-name ${STACK_NAME}
            """
          }
          catch (err) {
              echo "Caught: ${err}"
              throw new Exception("Wait for Stack Creation Failure!")
          }
        }
      }
    }

    stage('Configure Cache-Queue Instance') {
      environment {
        CQ_ASG_NAME = sh(script: '/usr/local/bin/get_output_from_stack ${STACK_NAME} CQASGName us-east-2 prod', returnStdout: true).trim()
      }
      steps {
        echo "=> Get Cach-Queue EC2 Private IP Address from ASG ${CQ_ASG_NAME}"
        script {
          env.CQ_PRIVATE_IP = sh(script: '/usr/local/bin/get_ip_from_asg ${CQ_ASG_NAME} us-east-2 prod', returnStdout: true).trim()
        }
        echo "=> Update CFN Stack with CQ Private IP Address ${CQ_PRIVATE_IP}"
        sh "/usr/local/bin/update_stack_prod ${STACK_NAME} '{\"CQPrivateIP\":\"${CQ_PRIVATE_IP}\"}'"
      }
    }

    stage('Deploy Frontend') {
      environment {
        FE_DOMAIN = "${PROJECT}-${params.TENANT}.${DOMAIN}"
      }
      steps {
        echo "=> Deploy Frontend Package ${params.FE_RELEASE_VERSION} to ${params.TENANT}.${DOMAIN}"
        sh '/usr/local/bin/aws s3 cp s3://${ATH_S3_ARTIFACTS_BUCKET}/athena/frontend/release/${FE_RELEASE_VERSION}.tar.gz .'
        sh 'tar zxvf ${FE_RELEASE_VERSION}.tar.gz'

        echo "==> Update config in assets/${env.CONFIG_FILE}.json"
        dir('dist/assets') {
          sh 'cp ${FE_CONFIG_FILE}.json /tmp/${FE_CONFIG_FILE}.${TENANT}.json'
          sh "update-fe-config ${FE_CONFIG_FILE} ${FE_RELEASE_VERSION} ${TENANT} ${ENV}"
          sh 'cp /tmp/${FE_CONFIG_FILE}.${TENANT}.json ${FE_CONFIG_FILE}.json'
        }

        echo "==> Deploy Athena Frontend for ${params.TENANT}"
        echo "==> Remove files on s3://${FE_DOMAIN}"
        dir('dist') {
          sh '''#!/bin/bash -xe
            $AWS_CMD s3 rm s3://${FE_DOMAIN} --recursive
          '''
          echo "==> Upload files to s3://${FE_DOMAIN}"
          sh '''#!/bin/bash -xe
            $AWS_CMD s3 cp --acl public-read --recursive . s3://${FE_DOMAIN}/
          '''
          echo "==> Set Cache-Control for Service Worker"
          sh '''#!/bin/bash -xe
            $AWS_CMD s3 cp --acl public-read --cache-control max-age=0 ./index.html s3://${FE_DOMAIN}/
            $AWS_CMD s3 cp --acl public-read --cache-control max-age=0 ./ngsw-worker.js s3://${FE_DOMAIN}/
          '''
        }
      }
    }
    
  }

  post {
    always {
      echo '==> Clean up built after run'
    }
    success {
      echo "Deploy success for ${ENV} - Tenant: ${params.TENANT}"
      script {
        env.DURATION = currentBuild.durationString.split(' and ')[0]
      }
      echo "==> Send Success Message to Hangout"
      // hangoutsNotify message: "Deploy *${currentBuild.result}*\nTenant: ${params.TENANT}\nEnvironment: ${ENV}\nDuration: ${DURATION}\nSite URL: https://${PROJECT}-${params.TENANT}.${DOMAIN}",
      //   token: "${ATH_ENV_GCHAT_TOKEN}", threadByJob: true
    }
    failure {
      echo "Deploy failed for ${ENV} - Tenant: ${params.TENANT}"
      script {
        env.DURATION = currentBuild.durationString.split(' and ')[0]
      }
      echo "==> Send Failure Message to Hangout"
      // hangoutsNotify message: "Deploy *${currentBuild.result}*\nTenant: ${params.TENANT}\nEnvironment: ${ENV}\nDuration: ${DURATION}",
      //   token: "${ATH_ENV_GCHAT_TOKEN}", threadByJob: true
    }
  }
}