---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
  namespace: ktvn
spec:
  limits:
  - default:
      memory: 2048Mi
      cpu: 500m
    defaultRequest:
      memory: 1024Mi
      cpu: 200m
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources-quota
  namespace: ktvn
spec:
  hard:
    requests.cpu: "8" 
    requests.memory: 22Gi 
    limits.cpu: "12" 
    limits.memory: 36Gi 